language: node_js
node_js:
- '7'
- '8'
notifications:
  slack:
    rooms:
      secure: uFuBVrhnCb/9qvnM+cyZ+jLqsHuGBKcJEaoS9hty6xIxmy0SeUhKRlmXFGJ+GHdzCI7rbrST6Z4TwhmxSAGML175YIdjxqzl6TS4ll7PunOdBFHpKmq4QTW9JaW0zwRGsSebemeaIhad8OFKhIL9uj0YyLGBNZpQflGt228HfC6EedIQhHLF43TfClogMeDu1EU3vKyUuB8BgCoj+q/NQD1FNmJhvajPupPR70+KCLovgODt8eCPAk1eWgBenSFenuqs2YTAOldansDXg/l/wjGzQBjxB1Wh4cN96CybNnSl+le8CRtF6MfBkXB++mT/hp/Q+1M+M6MCHSmt0JwQyZKyHuwSo1ok6Yr0v9S/1m8xevSnlrtc611nQ9pznWCBTM1R9DdJ5KYWjXonP46i7GMeIPy5Z3Y02WuAaRIwmbOOfBVuXBSN+1lnp/svRixtmE+x31R40E1jWEea+RkhgJOPVq4708jtoiBS29EtrGPVxkBId9o2LKbkAKtXWU1/l0wFN4YIHBWNWSJ6fmyKJXRjmP2TUGoGdWUNJ7CBT6Fx3Ut5HtsC4O85SCBEmfVPHOV/QiEU1DMeUVlzxKhcXsBQAF6XDMXSOFvDyGJMUcEa96VKcc8X4en4+LVNDvw54Jy3NyG0jEWZPd4JFENJj0QqVl2gPYP3USMSPL4LwVE=
